name: Deploy Prod

on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # githubからチェックアウト
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Configure AWS Credentials # AWSアクセス権限設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR # ECRログイン処理
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: WEB Build, tag, and push image to Amazon ECR # WEBコンテナビルド〜ECRにPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: common-prod-event-web
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./web/Dockerfile_prod .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: APP Build, tag, and push image to Amazon ECR # APPコンテナビルド〜ECRにPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: common-prod-event-app
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./app/Dockerfile_prod .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: BATCH Build, tag, and push image to Amazon ECR # BATCHコンテナビルド〜ECRにPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: common-prod-event-batch
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./batch/Dockerfile_prod .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Download task definition # タスク定義取得
        run: |
          aws ecs describe-task-definition --task-definition common-prod-event --query taskDefinition > task-definition.json
      - name: Render Amazon ECS task definition for first container # WEBタスク定義更新
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: common-prod-event-web
          image: 207095571838.dkr.ecr.ap-northeast-1.amazonaws.com/common-prod-event-web
      - name: Modify Amazon ECS task definition with second container # APPタスク定義更新
        id: render-app-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          container-name: common-prod-event-app
          image: 207095571838.dkr.ecr.ap-northeast-1.amazonaws.com/common-prod-event-app
      - name: Deploy to Amazon ECS service # コンテナデプロイ
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-app-container.outputs.task-definition }}
          service: common-prod-event
          cluster: common-prod-event
          wait-for-service-stability: true
